package io.b2mash.b2b.b2bstrawman.automation;

public enum TriggerType {
  TASK_STATUS_CHANGED,
  PROJECT_STATUS_CHANGED,
  CUSTOMER_STATUS_CHANGED,
  INVOICE_STATUS_CHANGED,
  TIME_ENTRY_CREATED,
  BUDGET_THRESHOLD_REACHED,
  DOCUMENT_ACCEPTED,
  INFORMATION_REQUEST_COMPLETED,
  PROPOSAL_SENT
}
