"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  fetchGeneratedDocumentsAction,
  deleteGeneratedDocumentAction,
  getDownloadUrlAction,
} from "@/app/(app)/org/[slug]/settings/templates/actions";
import { formatDate } from "@/lib/format";
import type { TemplateEntityType, GeneratedDocumentListResponse } from "@/lib/types";

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

interface GeneratedDocumentsListProps {
  entityType: TemplateEntityType;
  entityId: string;
  slug: string;
  isAdmin?: boolean;
}

export function GeneratedDocumentsList({
  entityType,
  entityId,
  isAdmin = false,
}: GeneratedDocumentsListProps) {
  const [documents, setDocuments] = useState<GeneratedDocumentListResponse[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null);

  const fetchDocuments = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await fetchGeneratedDocumentsAction(entityType, entityId);
      if (result.success && result.data) {
        setDocuments(result.data);
      } else {
        setError(result.error ?? "Failed to load generated documents.");
      }
    } catch {
      setError("An unexpected error occurred.");
    } finally {
      setIsLoading(false);
    }
  }, [entityType, entityId]);

  useEffect(() => {
    fetchDocuments();
  }, [fetchDocuments]);

  // Expose refetch for parent components
  useEffect(() => {
    // Re-fetch when entityId changes (e.g., after saving a new document)
  }, [entityId]);

  async function handleDownload(docId: string) {
    try {
      const result = await getDownloadUrlAction(docId);
      if (result.success && result.url) {
        window.open(result.url, "_blank");
      }
    } catch {
      // Silent fail — download will just not work
    }
  }

  async function handleDelete() {
    if (!deleteTargetId) return;
    setDeletingId(deleteTargetId);
    try {
      const result = await deleteGeneratedDocumentAction(deleteTargetId);
      if (result.success) {
        setDocuments((prev) => prev.filter((d) => d.id !== deleteTargetId));
      } else {
        setError(result.error ?? "Failed to delete document.");
      }
    } catch {
      setError("An unexpected error occurred.");
    } finally {
      setDeletingId(null);
      setDeleteDialogOpen(false);
      setDeleteTargetId(null);
    }
  }

  // Expose refetch for parent to call after "Save to Documents"
  // Using a global callback pattern since we can't use ref with function components easily
  (GeneratedDocumentsList as unknown as { refetch?: () => void }).refetch = fetchDocuments;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <p className="text-sm text-slate-500">Loading generated documents...</p>
      </div>
    );
  }

  if (documents.length === 0) {
    return (
      <div className="flex items-center justify-center py-12">
        <p className="text-sm text-slate-500">No documents generated yet</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {error && <p className="text-sm text-destructive">{error}</p>}

      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Template Name</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Date</TableHead>
            <TableHead>File Size</TableHead>
            <TableHead className="w-[100px]">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {documents.map((doc) => (
            <TableRow key={doc.id}>
              <TableCell className="font-medium">{doc.templateName}</TableCell>
              <TableCell>{doc.generatedBy}</TableCell>
              <TableCell>{formatDate(doc.generatedAt)}</TableCell>
              <TableCell>{formatFileSize(doc.fileSize)}</TableCell>
              <TableCell>
                <div className="flex items-center gap-1">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="size-8"
                    onClick={() => handleDownload(doc.id)}
                    title="Download"
                  >
                    <Download className="size-4" />
                  </Button>
                  {isAdmin && (
                    <AlertDialog
                      open={deleteDialogOpen && deleteTargetId === doc.id}
                      onOpenChange={(open) => {
                        setDeleteDialogOpen(open);
                        if (!open) setDeleteTargetId(null);
                      }}
                    >
                      <AlertDialogTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="size-8 text-red-600 hover:bg-red-50 hover:text-red-700 dark:text-red-400 dark:hover:bg-red-950 dark:hover:text-red-300"
                          onClick={() => {
                            setDeleteTargetId(doc.id);
                            setDeleteDialogOpen(true);
                          }}
                          title="Delete"
                        >
                          <Trash2 className="size-4" />
                        </Button>
                      </AlertDialogTrigger>
                      <AlertDialogContent>
                        <AlertDialogHeader>
                          <AlertDialogTitle>Delete Generated Document</AlertDialogTitle>
                          <AlertDialogDescription>
                            Are you sure you want to delete this generated document? This
                            action cannot be undone.
                          </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                          <AlertDialogCancel disabled={!!deletingId}>
                            Cancel
                          </AlertDialogCancel>
                          <Button
                            variant="destructive"
                            onClick={handleDelete}
                            disabled={!!deletingId}
                          >
                            {deletingId ? "Deleting..." : "Delete"}
                          </Button>
                        </AlertDialogFooter>
                      </AlertDialogContent>
                    </AlertDialog>
                  )}
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
