"use client";

import { useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { TemplateEntityType } from "@/lib/types";

interface VariableGroup {
  label: string;
  variables: { name: string; description: string }[];
}

const PROJECT_VARIABLES: VariableGroup[] = [
  {
    label: "Project",
    variables: [
      { name: "project.name", description: "Project name" },
      { name: "project.description", description: "Project description" },
      { name: "project.status", description: "Project status" },
      { name: "project.createdAt", description: "Project creation date" },
    ],
  },
  {
    label: "Customer",
    variables: [
      { name: "customer.name", description: "Customer name" },
      { name: "customer.email", description: "Customer email" },
      { name: "customer.phone", description: "Customer phone" },
      { name: "customer.idNumber", description: "Customer ID number" },
    ],
  },
  {
    label: "Lead",
    variables: [
      { name: "lead.name", description: "Project lead name" },
      { name: "lead.email", description: "Project lead email" },
    ],
  },
  {
    label: "Members (array)",
    variables: [
      { name: "members[].name", description: "Member name" },
      { name: "members[].email", description: "Member email" },
      { name: "members[].role", description: "Member role" },
    ],
  },
  {
    label: "Budget",
    variables: [
      { name: "budget.totalAmount", description: "Budget total amount" },
      { name: "budget.currency", description: "Budget currency" },
      { name: "budget.alertThreshold", description: "Alert threshold percentage" },
    ],
  },
  {
    label: "Tags (array)",
    variables: [
      { name: "tags[].name", description: "Tag name" },
      { name: "tags[].color", description: "Tag color" },
    ],
  },
  {
    label: "Organization",
    variables: [
      { name: "org.name", description: "Organization name" },
      { name: "org.logoUrl", description: "Organization logo URL" },
      { name: "org.brandColor", description: "Brand color (hex)" },
      { name: "org.documentFooterText", description: "Document footer text" },
    ],
  },
  {
    label: "Generation Info",
    variables: [
      { name: "generatedAt", description: "Generation timestamp" },
      { name: "generatedBy.name", description: "Generated by (name)" },
      { name: "generatedBy.email", description: "Generated by (email)" },
    ],
  },
];

const CUSTOMER_VARIABLES: VariableGroup[] = [
  {
    label: "Customer",
    variables: [
      { name: "customer.name", description: "Customer name" },
      { name: "customer.email", description: "Customer email" },
      { name: "customer.phone", description: "Customer phone" },
      { name: "customer.idNumber", description: "Customer ID number" },
      { name: "customer.status", description: "Customer status" },
    ],
  },
  {
    label: "Projects (array)",
    variables: [
      { name: "projects[].id", description: "Project ID" },
      { name: "projects[].name", description: "Project name" },
      { name: "projects[].status", description: "Project status" },
    ],
  },
  {
    label: "Tags (array)",
    variables: [
      { name: "tags[].name", description: "Tag name" },
      { name: "tags[].color", description: "Tag color" },
    ],
  },
  {
    label: "Organization",
    variables: [
      { name: "org.name", description: "Organization name" },
      { name: "org.logoUrl", description: "Organization logo URL" },
      { name: "org.brandColor", description: "Brand color (hex)" },
      { name: "org.documentFooterText", description: "Document footer text" },
    ],
  },
  {
    label: "Generation Info",
    variables: [
      { name: "generatedAt", description: "Generation timestamp" },
      { name: "generatedBy.name", description: "Generated by (name)" },
      { name: "generatedBy.email", description: "Generated by (email)" },
    ],
  },
];

const INVOICE_VARIABLES: VariableGroup[] = [
  {
    label: "Invoice",
    variables: [
      { name: "invoice.invoiceNumber", description: "Invoice number" },
      { name: "invoice.issueDate", description: "Issue date" },
      { name: "invoice.dueDate", description: "Due date" },
      { name: "invoice.status", description: "Invoice status" },
      { name: "invoice.totalAmount", description: "Total amount" },
      { name: "invoice.currency", description: "Currency" },
    ],
  },
  {
    label: "Line Items (array)",
    variables: [
      { name: "lines[].description", description: "Line description" },
      { name: "lines[].quantity", description: "Quantity" },
      { name: "lines[].unitPrice", description: "Unit price" },
      { name: "lines[].amount", description: "Line amount" },
    ],
  },
  {
    label: "Customer",
    variables: [
      { name: "customer.name", description: "Customer name" },
      { name: "customer.email", description: "Customer email" },
      { name: "customer.phone", description: "Customer phone" },
      { name: "customer.idNumber", description: "Customer ID number" },
    ],
  },
  {
    label: "Project",
    variables: [
      { name: "project.name", description: "Project name" },
      { name: "project.description", description: "Project description" },
    ],
  },
  {
    label: "Organization",
    variables: [
      { name: "org.name", description: "Organization name" },
      { name: "org.logoUrl", description: "Organization logo URL" },
      { name: "org.brandColor", description: "Brand color (hex)" },
      { name: "org.documentFooterText", description: "Document footer text" },
    ],
  },
  {
    label: "Generation Info",
    variables: [
      { name: "generatedAt", description: "Generation timestamp" },
      { name: "generatedBy.name", description: "Generated by (name)" },
      { name: "generatedBy.email", description: "Generated by (email)" },
    ],
  },
];

const VARIABLES_BY_TYPE: Record<TemplateEntityType, VariableGroup[]> = {
  PROJECT: PROJECT_VARIABLES,
  CUSTOMER: CUSTOMER_VARIABLES,
  INVOICE: INVOICE_VARIABLES,
};

interface TemplateVariableReferenceProps {
  entityType: TemplateEntityType;
}

export function TemplateVariableReference({
  entityType,
}: TemplateVariableReferenceProps) {
  const [expanded, setExpanded] = useState(false);
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set());

  const groups = VARIABLES_BY_TYPE[entityType] ?? [];

  function toggleGroup(label: string) {
    setExpandedGroups((prev) => {
      const next = new Set(prev);
      if (next.has(label)) {
        next.delete(label);
      } else {
        next.add(label);
      }
      return next;
    });
  }

  return (
    <div className="rounded-lg border border-slate-200 dark:border-slate-800">
      <Button
        type="button"
        variant="plain"
        className="w-full justify-between px-4 py-3"
        onClick={() => setExpanded(!expanded)}
      >
        <span className="text-sm font-medium text-slate-950 dark:text-slate-50">
          Variable Reference
        </span>
        {expanded ? (
          <ChevronDown className="size-4 text-slate-400" />
        ) : (
          <ChevronRight className="size-4 text-slate-400" />
        )}
      </Button>

      {expanded && (
        <div className="border-t border-slate-200 px-4 py-3 dark:border-slate-800">
          <p className="mb-3 text-xs text-slate-500 dark:text-slate-400">
            Use these placeholders in your template content. Syntax:{" "}
            <code className="rounded bg-slate-100 px-1 dark:bg-slate-800">
              {"${variable.name}"}
            </code>
          </p>
          <div className="space-y-2">
            {groups.map((group) => (
              <div key={group.label}>
                <button
                  type="button"
                  className="flex w-full items-center gap-1 text-left text-xs font-semibold text-slate-700 dark:text-slate-300"
                  onClick={() => toggleGroup(group.label)}
                >
                  {expandedGroups.has(group.label) ? (
                    <ChevronDown className="size-3" />
                  ) : (
                    <ChevronRight className="size-3" />
                  )}
                  {group.label}
                </button>
                {expandedGroups.has(group.label) && (
                  <div className="ml-4 mt-1 space-y-0.5">
                    {group.variables.map((v) => (
                      <div
                        key={v.name}
                        className="flex items-baseline justify-between gap-2"
                      >
                        <code className="text-xs text-teal-600 dark:text-teal-400">
                          {v.name}
                        </code>
                        <span className="text-xs text-slate-400">
                          {v.description}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
