export const TERMINOLOGY: Record<string, Record<string, string>> = {
  "accounting-za": {
    Project: "Engagement",
    Projects: "Engagements",
    project: "engagement",
    projects: "engagements",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Rate Card": "Fee Schedule",
    "Rate Cards": "Fee Schedules",
  },
  "legal-za": {
    Project: "Matter",
    Projects: "Matters",
    project: "matter",
    projects: "matters",
    Task: "Work Item",
    Tasks: "Work Items",
    task: "work item",
    tasks: "work items",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Time Entry": "Fee Note",
    "Time Entries": "Fee Notes",
    "Rate Card": "Tariff Schedule",
    "Rate Cards": "Tariff Schedules",
    Document: "Pleading",
    Documents: "Pleadings",
  },
};
