export const TERMINOLOGY: Record<string, Record<string, string>> = {
  "consulting-za": {
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    "Time Entry": "Time Log",
    "Time Entries": "Time Logs",
    "time entry": "time log",
    "time entries": "time logs",
    "Rate Card": "Billing Rates",
    "Rate Cards": "Billing Rates",
    "rate card": "billing rates",
    "rate cards": "billing rates",
    "Time Tracking": "Time Logs",
    "Rates & Currency": "Billing Rates",
    "project.namePlaceholder": "e.g. Q4 Strategy Engagement",
    "project.referencePlaceholder": "e.g. ENG-2026-001",
  },
  "accounting-za": {
    Project: "Engagement",
    Projects: "Engagements",
    project: "engagement",
    projects: "engagements",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Rate Card": "Fee Schedule",
    "Rate Cards": "Fee Schedules",
    "Active Projects": "Active Engagements",
    "Project Health": "Engagement Health",
    "Project Profitability": "Engagement Profitability",
    "Create Customer": "Create Client",
    "Activate Customer": "Activate Client",
    "Offboard Customer": "Offboard Client",
    "project.namePlaceholder": "e.g. FY2026 Audit",
    "project.referencePlaceholder": "e.g. ENG-2026-001",
  },
  "legal-za": {
    Project: "Matter",
    Projects: "Matters",
    project: "matter",
    projects: "matters",
    Task: "Action Item",
    Tasks: "Action Items",
    task: "action item",
    tasks: "action items",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Time Entry": "Time Recording",
    "Time Entries": "Time Recordings",
    "time entry": "time recording",
    "time entries": "time recordings",
    "Rate Card": "Tariff Schedule",
    "Rate Cards": "Tariff Schedules",
    Invoice: "Fee Note",
    Invoices: "Fee Notes",
    invoice: "fee note",
    invoices: "fee notes",
    Expense: "Disbursement",
    Expenses: "Disbursements",
    expense: "disbursement",
    expenses: "disbursements",
    Budget: "Fee Estimate",
    Budgets: "Fee Estimates",
    budget: "fee estimate",
    budgets: "fee estimates",
    Retainer: "Mandate",
    Retainers: "Mandates",
    retainer: "mandate",
    retainers: "mandates",
    "Active Projects": "Active Matters",
    "Project Health": "Matter Health",
    "Project Profitability": "Matter Profitability",
    "Create Customer": "Create Client",
    "Activate Customer": "Activate Client",
    "Offboard Customer": "Offboard Client",
    "project.namePlaceholder": "e.g. Dlamini v Road Accident Fund",
    "project.referencePlaceholder": "e.g. RAF-2026-001",
    "audit.tab": "Audit Trail",
  },
};

/**
 * Resolve the audit tab label, falling back to "Audit" when no terminology
 * mapping is present. The terminology hook returns the literal key when no
 * profile maps it — so we substitute a sensible default at the call site.
 */
export function auditTabLabel(t: (term: string) => string): string {
  const v = t("audit.tab");
  return v === "audit.tab" ? "Audit" : v;
}
