export const TERMINOLOGY: Record<string, Record<string, string>> = {
  "accounting-za": {
    Project: "Engagement",
    Projects: "Engagements",
    project: "engagement",
    projects: "engagements",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Rate Card": "Fee Schedule",
    "Rate Cards": "Fee Schedules",
    "Active Projects": "Active Engagements",
    "Project Health": "Engagement Health",
    "Project Profitability": "Engagement Profitability",
    "Create Customer": "Create Client",
    "Activate Customer": "Activate Client",
    "Offboard Customer": "Offboard Client",
  },
  "legal-za": {
    Project: "Matter",
    Projects: "Matters",
    project: "matter",
    projects: "matters",
    Task: "Action Item",
    Tasks: "Action Items",
    task: "action item",
    tasks: "action items",
    Customer: "Client",
    Customers: "Clients",
    customer: "client",
    customers: "clients",
    Proposal: "Engagement Letter",
    Proposals: "Engagement Letters",
    proposal: "engagement letter",
    proposals: "engagement letters",
    "Time Entry": "Time Recording",
    "Time Entries": "Time Recordings",
    "time entry": "time recording",
    "time entries": "time recordings",
    "Rate Card": "Tariff Schedule",
    "Rate Cards": "Tariff Schedules",
    Invoice: "Fee Note",
    Invoices: "Fee Notes",
    invoice: "fee note",
    invoices: "fee notes",
    Expense: "Disbursement",
    Expenses: "Disbursements",
    expense: "disbursement",
    expenses: "disbursements",
    Budget: "Fee Estimate",
    Budgets: "Fee Estimates",
    budget: "fee estimate",
    budgets: "fee estimates",
    Retainer: "Mandate",
    Retainers: "Mandates",
    retainer: "mandate",
    retainers: "mandates",
    "Active Projects": "Active Matters",
    "Project Health": "Matter Health",
    "Project Profitability": "Matter Profitability",
    "Create Customer": "Create Client",
    "Activate Customer": "Activate Client",
    "Offboard Customer": "Offboard Client",
  },
};
